### ISSUE TITLE
缺少dll

### ISSUE THREAD

**Issue by yefuchao** [itsvse/aliyun-net-sdk-dysms-demo#1]
aliyun-net-sdk-dysms这个包哪来的？

**Comment by itsvse** [comment]
https://github.com/itsvse/aliyun-openapi-net-sdk/tree/master/aliyun-net-sdk-dysms

这是我自己写的

**Comment by itsvse** [comment]
https://github.com/itsvse/aliyun-net-sdk-dysms-demo/releases   这里面有dll

**Comment by yefuchao** [comment]
Got it
